name: Build and push Image - Release

on:
  push:
    tags:
      - '*'
  schedule:
    - cron: '0 2 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
        
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: stivik/oidc-forward-auth
          auto_tag: true